export interface ConversionFAQ { q: string; a: string }
export interface ConversionAlternative { name: string; issue: string }

export interface ConversionConfig {
  slug: string;
  fromFormat: string;
  toFormat: string;
  toolHref: string;
  category: "image" | "pdf";
  accentColor: string;
  title: string;
  metaDescription: string;
  h1: string;
  intro: string;
  steps: { title: string; desc: string }[];
  useCases: string[];
  alternatives: ConversionAlternative[];
  faq: ConversionFAQ[];
  relatedSlugs: string[];
}

export const CONVERSIONS: ConversionConfig[] = [
  {
    slug: "jpg-to-png",
    fromFormat: "JPG",
    toFormat: "PNG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-blue-500 to-cyan-500",
    title: "JPG to PNG Converter — Free, No Upload, No Signup",
    metaDescription: "Convert JPG to PNG instantly in your browser. No upload, no signup, no file size limit. Lossless PNG output. Free forever.",
    h1: "Convert JPG to PNG — Free & Private",
    intro: "Need to convert a JPG image to PNG? ToolsHub converts JPG to PNG entirely in your browser — your image never leaves your device. PNG is a lossless format, so the converted file will have higher quality than the original JPG at zero extra cost. Ideal for images that need transparency support or will be re-edited.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the free Image Converter tool." },
      { title: "Upload your JPG file", desc: "Drag and drop your JPG image or click to select it from your device." },
      { title: "Select PNG as output", desc: "Choose PNG from the format dropdown and click Convert." },
      { title: "Download your PNG", desc: "Your PNG file is ready instantly. Click Download to save it." },
    ],
    useCases: [
      "Convert photos to PNG before editing in Photoshop or GIMP",
      "Convert JPG screenshots to PNG for crisper text rendering",
      "Convert product images to PNG to support transparent backgrounds",
      "Convert JPG logos to PNG for use in presentations and documents",
      "Convert photos to PNG before uploading to platforms that require PNG",
    ],
    alternatives: [
      { name: "Cloudconvert", issue: "Uploads your file to a remote server — privacy risk for sensitive images" },
      { name: "Convertio", issue: "Requires sign-up for larger files; files stored on their servers for 24 hours" },
      { name: "ILoveIMG", issue: "Server-side processing; daily conversion limits on free tier" },
    ],
    faq: [
      { q: "Is converting JPG to PNG free?", a: "Yes. ToolsHub JPG to PNG conversion is completely free, no signup required, with no file size or quantity limits." },
      { q: "Does JPG to PNG conversion improve quality?", a: "Conversion to PNG stops further quality loss because PNG is lossless. However, quality lost during the original JPG compression cannot be recovered." },
      { q: "Does the PNG file support transparency?", a: "Converting a JPG to PNG does not add transparency — JPG has no transparency channel. To remove a background and get a transparent PNG, use the Background Remover tool." },
      { q: "Is my JPG file uploaded to a server?", a: "No. Conversion happens entirely in your browser using the HTML5 Canvas API. Your file is never sent to any server." },
      { q: "Can I convert multiple JPG files to PNG at once?", a: "Yes. The Image Converter supports batch conversion. Upload multiple JPGs and download them all as a single ZIP file." },
    ],
    relatedSlugs: ["png-to-jpg", "jpg-to-webp", "webp-to-png"],
  },
  {
    slug: "png-to-jpg",
    fromFormat: "PNG",
    toFormat: "JPG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-pink-500 to-rose-500",
    title: "PNG to JPG Converter — Free, Instant, No Upload",
    metaDescription: "Convert PNG to JPG free in your browser. Adjust quality, no server upload, no signup. Smaller file size with great quality.",
    h1: "Convert PNG to JPG — Free & Private",
    intro: "Converting PNG to JPG reduces file size significantly, making images load faster on websites and easier to share. ToolsHub runs the entire conversion in your browser — no files are uploaded to any server. Choose your quality level (we recommend 85–90% for a great balance of quality and size) and download your JPG instantly.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the free Image Converter tool." },
      { title: "Upload your PNG file", desc: "Drag and drop your PNG image or click to select it." },
      { title: "Select JPG and set quality", desc: "Choose JPG from the format dropdown. Adjust quality (85% recommended)." },
      { title: "Download your JPG", desc: "Click Convert and then Download to save your smaller JPG file." },
    ],
    useCases: [
      "Reduce PNG file size for faster website page loads",
      "Convert PNG screenshots to JPG before emailing or messaging",
      "Convert PNG product images to JPG for e-commerce platforms",
      "Shrink PNG illustrations to JPG for social media posts",
      "Convert PNG exports from design tools to JPG for print-ready files",
    ],
    alternatives: [
      { name: "TinyPNG", issue: "Compresses PNGs but doesn't convert to JPG; server-side upload required" },
      { name: "ILoveIMG", issue: "Uploads to their servers; limited free conversions per day" },
      { name: "Squoosh (Google)", issue: "One image at a time; no batch processing" },
    ],
    faq: [
      { q: "Will converting PNG to JPG reduce quality?", a: "Yes, slightly. JPG is lossy, so some detail is lost. At 85–90% quality, the difference is virtually invisible to the human eye." },
      { q: "How much smaller will the JPG be?", a: "Typically 60–80% smaller than the original PNG for photographs. Flat graphics and screenshots may see less reduction." },
      { q: "Can I convert a PNG with a transparent background to JPG?", a: "Yes, but transparency is not supported in JPG. Transparent areas will be filled with white (or the background color you choose)." },
      { q: "Is the PNG uploaded to a server?", a: "No. Everything runs locally in your browser using the Canvas API. Your PNG never leaves your device." },
      { q: "Can I batch convert PNGs to JPG?", a: "Yes. Upload multiple PNG files and download all JPGs as a ZIP." },
    ],
    relatedSlugs: ["jpg-to-png", "png-to-webp", "webp-to-jpg"],
  },
  {
    slug: "webp-to-png",
    fromFormat: "WebP",
    toFormat: "PNG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-violet-500 to-purple-600",
    title: "WebP to PNG Converter — Free, Browser-Based, No Upload",
    metaDescription: "Convert WebP to PNG free online. No upload, no signup. Download full-quality PNG from any WebP image instantly.",
    h1: "Convert WebP to PNG — Free & Private",
    intro: "WebP images are great for web performance, but many apps and older browsers can't open them. Converting WebP to PNG gives you a universally compatible image that works everywhere — in Photoshop, Figma, Word, and every operating system. ToolsHub does this entirely in your browser with zero uploads.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the free Image Converter." },
      { title: "Upload your WebP file", desc: "Drag and drop your WebP image or click to select it." },
      { title: "Select PNG as the output format", desc: "Choose PNG from the format selector." },
      { title: "Download the PNG", desc: "Click Convert, then Download your PNG immediately." },
    ],
    useCases: [
      "Convert WebP images downloaded from websites for editing in Photoshop",
      "Convert WebP to PNG for use in Microsoft Office documents",
      "Convert product images from websites that serve WebP to editable PNG",
      "Convert WebP screenshots to PNG for cross-platform sharing",
      "Convert WebP graphics for use in apps that don't support WebP",
    ],
    alternatives: [
      { name: "Convertio", issue: "Server-side conversion; files stored temporarily on their cloud" },
      { name: "CloudConvert", issue: "Free tier has daily limits; uploads to external servers" },
      { name: "Online image editors", issue: "Require accounts and are much more complex than a simple format conversion" },
    ],
    faq: [
      { q: "Why can't I open WebP files on Windows?", a: "Older versions of Windows don't have a built-in WebP decoder. Converting to PNG makes the file openable in Paint, Photoshop, and all Windows apps." },
      { q: "Does converting WebP to PNG lose quality?", a: "No. PNG is lossless. If the WebP was lossless, the conversion preserves full quality. If the WebP was lossy, PNG captures whatever quality was there without further loss." },
      { q: "Is my WebP file uploaded to any server?", a: "No. The conversion uses the HTML5 Canvas API entirely in your browser. Your file stays on your device." },
      { q: "Can I convert multiple WebP files at once?", a: "Yes. The batch converter lets you upload multiple WebP files and download them all as a ZIP." },
      { q: "Does WebP to PNG preserve transparency?", a: "Yes. If the WebP has a transparent (alpha) channel, it will be preserved in the PNG output." },
    ],
    relatedSlugs: ["png-to-webp", "webp-to-jpg", "jpg-to-png"],
  },
  {
    slug: "png-to-webp",
    fromFormat: "PNG",
    toFormat: "WebP",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-emerald-500 to-teal-500",
    title: "PNG to WebP Converter — Free, Fast, No Upload",
    metaDescription: "Convert PNG to WebP free. Smaller file sizes for faster websites. No upload, no signup, batch conversion included.",
    h1: "Convert PNG to WebP — Free & Private",
    intro: "WebP images are 25–35% smaller than PNG while maintaining the same visual quality. Converting your PNGs to WebP is one of the fastest ways to speed up your website. ToolsHub converts PNG to WebP in your browser — no uploads, no server, instant results.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the free tool." },
      { title: "Upload your PNG files", desc: "Select one or multiple PNG images." },
      { title: "Choose WebP output", desc: "Select WebP from the format dropdown and set quality." },
      { title: "Download as WebP or ZIP", desc: "Download individual WebP files or all as a ZIP." },
    ],
    useCases: [
      "Optimize website images for faster page load speeds",
      "Convert PNG assets to WebP for improved Core Web Vitals scores",
      "Reduce image bandwidth usage for mobile users",
      "Convert illustrations and graphics to WebP for Next.js or Nuxt apps",
      "Prepare WebP images for Google PageSpeed recommendations",
    ],
    alternatives: [
      { name: "Squoosh", issue: "One image at a time; no batch processing available" },
      { name: "cwebp CLI", issue: "Requires technical knowledge and command-line installation" },
      { name: "Photoshop WebP plugin", issue: "Requires paid Photoshop subscription and plugin setup" },
    ],
    faq: [
      { q: "How much smaller is WebP compared to PNG?", a: "WebP is typically 25–35% smaller than equivalent-quality PNG. For photos, savings can be even higher." },
      { q: "Does WebP support transparency like PNG?", a: "Yes. WebP supports an alpha channel, so transparent PNGs convert to transparent WebP files." },
      { q: "Is the conversion done on a server?", a: "No. The conversion runs entirely in your browser using the Canvas API. No file leaves your device." },
      { q: "Do all browsers support WebP?", a: "Yes. As of 2024, all major browsers (Chrome, Firefox, Safari, Edge) support WebP natively." },
      { q: "Can I batch convert PNGs to WebP?", a: "Yes. Upload multiple PNG files and download them all as WebP in a ZIP archive." },
    ],
    relatedSlugs: ["webp-to-png", "jpg-to-webp", "png-to-jpg"],
  },
  {
    slug: "webp-to-jpg",
    fromFormat: "WebP",
    toFormat: "JPG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-amber-500 to-orange-500",
    title: "WebP to JPG Converter — Free, Instant, No Upload",
    metaDescription: "Convert WebP to JPG free online. No upload, no signup, instant download. Compatible JPG output from any WebP image.",
    h1: "Convert WebP to JPG — Free & Private",
    intro: "Downloaded a WebP image from a website and can't open it? Convert it to JPG for universal compatibility. JPG works in every photo viewer, editor, and platform. ToolsHub converts WebP to JPG entirely in your browser — no file ever leaves your device.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to launch the converter." },
      { title: "Upload your WebP file", desc: "Drop your WebP image into the upload zone." },
      { title: "Choose JPG output", desc: "Select JPG and set your preferred quality level." },
      { title: "Download the JPG", desc: "Click Convert, then Download your JPG instantly." },
    ],
    useCases: [
      "Convert WebP images downloaded from websites for use in non-web apps",
      "Convert WebP to JPG for printing (most printers need JPG or PDF)",
      "Convert WebP graphics to JPG for use in email attachments",
      "Convert website WebP images to JPG for use in presentations",
      "Convert WebP files to JPG for uploading to platforms that only accept JPG",
    ],
    alternatives: [
      { name: "Cloudconvert", issue: "Requires account for bulk conversions; files uploaded to the cloud" },
      { name: "Paint (Windows)", issue: "Doesn't open WebP on older Windows versions without codec" },
      { name: "Preview (macOS)", issue: "Can open WebP but requires macOS Ventura or later" },
    ],
    faq: [
      { q: "Why download images as WebP instead of JPG?", a: "Websites serve WebP because it's smaller and loads faster. But WebP isn't universally supported outside browsers, so converting to JPG makes images usable everywhere." },
      { q: "Does converting WebP to JPG reduce quality?", a: "Slight quality loss occurs because JPG is lossy. At 90% quality, the difference is virtually invisible." },
      { q: "Is my WebP file sent to a server?", a: "No. Conversion runs locally in your browser using the Canvas API." },
      { q: "Can I batch convert WebP files to JPG?", a: "Yes. Upload multiple files and download all JPGs as a ZIP archive." },
      { q: "Does transparency get preserved?", a: "No. JPG doesn't support transparency. Transparent areas in the WebP become white in the JPG output." },
    ],
    relatedSlugs: ["jpg-to-webp", "webp-to-png", "png-to-jpg"],
  },
  {
    slug: "jpg-to-webp",
    fromFormat: "JPG",
    toFormat: "WebP",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-cyan-500 to-blue-600",
    title: "JPG to WebP Converter — Free, No Upload, Instant",
    metaDescription: "Convert JPG to WebP free. Smaller files for faster websites. No upload required, batch conversion, instant download.",
    h1: "Convert JPG to WebP — Free & Private",
    intro: "Converting your JPG images to WebP reduces file sizes by 25–35% without visible quality loss. This directly improves your website's page speed, Core Web Vitals score, and user experience. ToolsHub handles the conversion in your browser — no uploads, no servers, instant output.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the tool." },
      { title: "Upload your JPG files", desc: "Select one or multiple JPG images." },
      { title: "Choose WebP output", desc: "Select WebP from the format dropdown." },
      { title: "Download as WebP", desc: "Click Convert and download your optimized WebP files." },
    ],
    useCases: [
      "Optimize blog post images for faster load times",
      "Convert product photos to WebP for e-commerce speed improvements",
      "Reduce image bandwidth for mobile-first websites",
      "Convert JPGs to WebP for improved Lighthouse scores",
      "Prepare images for Next.js, Nuxt, or Astro image optimization pipelines",
    ],
    alternatives: [
      { name: "Google PageSpeed Insights", issue: "Identifies the problem but doesn't convert the images for you" },
      { name: "Squoosh", issue: "One image at a time — no batch processing" },
      { name: "Webpack image-webpack-loader", issue: "Requires developer setup and build pipeline configuration" },
    ],
    faq: [
      { q: "How much smaller will WebP be than the original JPG?", a: "Typically 25–35% smaller with the same visual quality. Larger images see even greater savings." },
      { q: "Will all browsers display my WebP images?", a: "Yes. Chrome, Firefox, Safari (v14+), and Edge all support WebP natively as of 2022." },
      { q: "Is the conversion private?", a: "Yes. Conversion runs entirely in your browser — no file is sent to any server." },
      { q: "Can I set the WebP quality?", a: "Yes. The Image Converter lets you choose the quality level (1–100%) before converting." },
      { q: "Can I batch convert JPGs to WebP?", a: "Yes. Upload multiple files and download them all as WebP in a single ZIP file." },
    ],
    relatedSlugs: ["jpg-to-png", "png-to-webp", "webp-to-jpg"],
  },
  {
    slug: "heic-to-jpg",
    fromFormat: "HEIC",
    toFormat: "JPG",
    toolHref: "/heic-converter",
    category: "image",
    accentColor: "from-orange-500 to-amber-500",
    title: "HEIC to JPG Converter — Free iPhone Photo Converter",
    metaDescription: "Convert HEIC to JPG free. iPhone photos to JPG instantly in your browser. No upload, no signup, batch convert & download as ZIP.",
    h1: "Convert HEIC to JPG — Free iPhone Photo Converter",
    intro: "iPhones and iPads save photos in HEIC format by default — it's more efficient than JPG. But HEIC isn't widely supported on Windows, Android, or most online platforms. Converting your HEIC photos to JPG makes them universally compatible. ToolsHub converts HEIC to JPG entirely in your browser using the heic2any library — your private photos are never uploaded.",
    steps: [
      { title: "Open the HEIC Converter", desc: "Click the button below to open the free HEIC to JPG tool." },
      { title: "Upload your HEIC photos", desc: "Drag and drop one or multiple HEIC files from your device." },
      { title: "Choose JPG output", desc: "Select JPG as the output format." },
      { title: "Download individually or as ZIP", desc: "Download converted JPGs one by one or all as a single ZIP file." },
    ],
    useCases: [
      "Convert iPhone photos to JPG before sharing with Windows or Android users",
      "Convert HEIC photos to upload to Instagram, Facebook, or Twitter",
      "Convert HEIC images for use in non-Apple design tools like Canva or Figma",
      "Convert HEIC photos for use in PowerPoint or Google Slides presentations",
      "Batch convert an entire iPhone photo export to JPG for archiving",
    ],
    alternatives: [
      { name: "iMazing HEIC Converter", issue: "Desktop app download required; only available for Mac/PC" },
      { name: "HEICtoJPEG.com", issue: "Uploads your private photos to their servers" },
      { name: "FreeConvert", issue: "Uploads to their servers; limited free conversions per day" },
    ],
    faq: [
      { q: "What is a HEIC file?", a: "HEIC (High Efficiency Image Container) is the photo format used by Apple devices since iOS 11. It's smaller than JPG but not supported everywhere." },
      { q: "Why can't Windows open HEIC files?", a: "Windows requires a paid HEVC codec to open HEIC files. Converting to JPG removes this dependency entirely." },
      { q: "Are my iPhone photos uploaded to a server?", a: "No. The heic2any library runs locally in your browser. Your photos never leave your device." },
      { q: "Can I convert multiple HEIC files at once?", a: "Yes. Drop multiple HEIC files and download them all as a ZIP." },
      { q: "Is quality lost when converting HEIC to JPG?", a: "Minimal. At 90% quality, the JPG is visually identical to the HEIC original for most photos." },
    ],
    relatedSlugs: ["heic-to-png", "heic-to-webp", "jpg-to-png"],
  },
  {
    slug: "heic-to-png",
    fromFormat: "HEIC",
    toFormat: "PNG",
    toolHref: "/heic-converter",
    category: "image",
    accentColor: "from-orange-500 to-rose-500",
    title: "HEIC to PNG Converter — Free, Browser-Based, No Upload",
    metaDescription: "Convert HEIC to PNG free online. Lossless PNG output from iPhone photos. No upload, no signup, batch conversion supported.",
    h1: "Convert HEIC to PNG — Free & Private",
    intro: "Need lossless PNG output from your iPhone HEIC photos? ToolsHub converts HEIC to PNG entirely in your browser. PNG is a lossless format — perfect for editing, design work, or any situation where you need maximum image quality without compression artifacts.",
    steps: [
      { title: "Open the HEIC Converter", desc: "Click the button below to open the HEIC to PNG converter." },
      { title: "Upload your HEIC files", desc: "Drag and drop your iPhone HEIC photos." },
      { title: "Select PNG output", desc: "Choose PNG from the output format options." },
      { title: "Download your PNG files", desc: "Download PNGs individually or all in a ZIP." },
    ],
    useCases: [
      "Convert iPhone photos to lossless PNG for professional photo editing",
      "Convert HEIC to PNG for use in Photoshop, GIMP, or Affinity Photo",
      "Convert HEIC screenshots from iOS devices to PNG",
      "Convert HEIC photos to PNG for web design work",
      "Archive iPhone photos as PNG for maximum quality preservation",
    ],
    alternatives: [
      { name: "iMazing HEIC Converter", issue: "Doesn't support PNG output; desktop app required" },
      { name: "Convertio", issue: "Uploads your private iPhone photos to their servers" },
      { name: "Adobe Lightroom", issue: "Requires a paid Creative Cloud subscription" },
    ],
    faq: [
      { q: "Why choose PNG over JPG for HEIC conversion?", a: "PNG is lossless — no quality is lost during conversion. Choose PNG when image quality is critical (e.g., for editing, design work, or archiving)." },
      { q: "Is the HEIC file uploaded anywhere?", a: "No. Conversion happens locally using the heic2any library in your browser." },
      { q: "Do HEIC files have transparency?", a: "Rarely. Most HEIC photos don't have transparency. If yours does, PNG output will preserve it." },
      { q: "Can I batch convert HEIC to PNG?", a: "Yes. Upload multiple HEIC files and download them all as PNG in a ZIP." },
      { q: "How large are the PNG files compared to HEIC?", a: "PNG files are significantly larger because they are lossless. A 3 MB HEIC may become a 15–20 MB PNG." },
    ],
    relatedSlugs: ["heic-to-jpg", "heic-to-webp", "webp-to-png"],
  },
  {
    slug: "heic-to-webp",
    fromFormat: "HEIC",
    toFormat: "WebP",
    toolHref: "/heic-converter",
    category: "image",
    accentColor: "from-amber-500 to-lime-500",
    title: "HEIC to WebP Converter — Free, No Upload",
    metaDescription: "Convert HEIC to WebP free. iPhone photos to optimized WebP for websites. No upload, no signup, instant conversion.",
    h1: "Convert HEIC to WebP — Free & Private",
    intro: "Convert your iPhone HEIC photos to WebP for optimized web use. WebP is smaller than both HEIC-derived JPG and PNG while keeping excellent visual quality. ToolsHub runs the conversion locally in your browser — no private photos are ever uploaded.",
    steps: [
      { title: "Open the HEIC Converter", desc: "Click the button below to open the converter." },
      { title: "Upload your HEIC files", desc: "Select one or more HEIC photos from your iPhone or iPad export." },
      { title: "Choose WebP output", desc: "Select WebP as the output format and set quality." },
      { title: "Download your WebP files", desc: "Download the optimized WebP images ready for web use." },
    ],
    useCases: [
      "Convert iPhone photos directly to WebP for use on websites",
      "Create optimized WebP product images from iPhone photography",
      "Convert HEIC photos to WebP for blog post illustrations",
      "Prepare iPhone event photos as WebP for web galleries",
      "Convert HEIC to WebP as part of a web content pipeline",
    ],
    alternatives: [
      { name: "Multi-step conversion (HEIC → JPG → WebP)", issue: "Double conversion causes additional quality loss and wasted time" },
      { name: "Cloudconvert", issue: "Uploads private iPhone photos to their cloud servers" },
      { name: "ImageMagick CLI", issue: "Requires technical setup; HEIC support requires additional libraries" },
    ],
    faq: [
      { q: "Can I convert directly from HEIC to WebP?", a: "Yes. ToolsHub converts HEIC to WebP in a single step — no intermediate format needed." },
      { q: "Is my photo uploaded to any server?", a: "No. The heic2any and Canvas APIs run entirely in your browser." },
      { q: "How does WebP quality compare to HEIC?", a: "At 80–90% quality, WebP is visually equivalent to the HEIC original for most photos, while being well-optimized for web use." },
      { q: "Do all browsers support WebP?", a: "Yes. All modern browsers (Chrome, Firefox, Safari 14+, Edge) support WebP natively." },
      { q: "Can I batch convert HEIC to WebP?", a: "Yes. Drop multiple HEIC files and download all WebP outputs in a ZIP." },
    ],
    relatedSlugs: ["heic-to-jpg", "heic-to-png", "jpg-to-webp"],
  },
  {
    slug: "jpeg-to-png",
    fromFormat: "JPEG",
    toFormat: "PNG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-blue-500 to-indigo-500",
    title: "JPEG to PNG Converter — Free, No Upload, Instant",
    metaDescription: "Convert JPEG to PNG free online. Lossless PNG output, no upload, no signup. Batch convert JPEG to PNG in your browser.",
    h1: "Convert JPEG to PNG — Free & Private",
    intro: "JPEG and JPG are the same format — JPEG is just the older file extension. Converting JPEG to PNG gives you a lossless image perfect for editing or transparency needs. ToolsHub handles this entirely in your browser without any file uploads.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the converter." },
      { title: "Upload your JPEG file", desc: "Select your .jpeg file from your device." },
      { title: "Select PNG output", desc: "Choose PNG from the format dropdown." },
      { title: "Download your PNG", desc: "Click Convert and save your PNG file." },
    ],
    useCases: [
      "Convert JPEG photos to PNG for editing in design software",
      "Convert JPEG screenshots to sharper PNG format",
      "Convert JPEG images to PNG for websites requiring lossless quality",
      "Convert JPEG logos to PNG for transparent background editing",
      "Convert JPEG exports to PNG for further image processing",
    ],
    alternatives: [
      { name: "GIMP", issue: "Full image editor — too complex for a simple format conversion" },
      { name: "Convertio", issue: "Uploads your file to their servers" },
      { name: "ILoveIMG", issue: "Daily limits on free tier; server-side processing" },
    ],
    faq: [
      { q: "Is JPEG the same as JPG?", a: "Yes. JPEG and JPG are the same image format. JPEG is the original extension (from MS-DOS 8.3 filename limits), while JPG is the shortened version. They are interchangeable." },
      { q: "Does JPEG to PNG conversion add transparency?", a: "No. Converting JPEG to PNG doesn't create transparency — it just changes the container to lossless. To remove a background and get transparency, use the Background Remover." },
      { q: "Is the file sent to a server?", a: "No. The conversion uses your browser's Canvas API. No data leaves your device." },
      { q: "Can I convert multiple JPEG files at once?", a: "Yes. The batch converter supports multiple files with ZIP download." },
      { q: "Will PNG be higher quality than the original JPEG?", a: "PNG stops further quality loss from re-encoding. But quality lost during the original JPEG compression cannot be recovered." },
    ],
    relatedSlugs: ["jpg-to-png", "png-to-jpg", "jpg-to-webp"],
  },
  {
    slug: "bmp-to-jpg",
    fromFormat: "BMP",
    toFormat: "JPG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-slate-500 to-gray-600",
    title: "BMP to JPG Converter — Free, No Upload, Instant",
    metaDescription: "Convert BMP to JPG free. Reduce large BMP file sizes to small JPG instantly in your browser. No upload, no signup.",
    h1: "Convert BMP to JPG — Free & Private",
    intro: "BMP files are uncompressed bitmaps — they're extremely large compared to JPG. A typical BMP can be 10–50x larger than its JPG equivalent. Converting BMP to JPG is one of the fastest ways to reduce file size while keeping great visual quality. ToolsHub does this entirely in your browser.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to launch the tool." },
      { title: "Upload your BMP file", desc: "Select your .bmp image from your device." },
      { title: "Choose JPG output", desc: "Select JPG and set your preferred quality." },
      { title: "Download the JPG", desc: "Save your converted, much-smaller JPG file." },
    ],
    useCases: [
      "Reduce massive BMP file sizes before sharing or emailing",
      "Convert BMP screenshots from older Windows apps to JPG",
      "Convert BMP images exported from legacy software to standard JPG",
      "Reduce storage space used by large BMP archives",
      "Convert BMP to JPG for upload to web platforms that reject BMP",
    ],
    alternatives: [
      { name: "Paint (Windows)", issue: "Can convert but requires extra steps; no batch processing" },
      { name: "IrfanView", issue: "Requires software installation on Windows" },
      { name: "Online converters", issue: "Most upload your file to their servers — privacy concern for sensitive images" },
    ],
    faq: [
      { q: "Why are BMP files so large?", a: "BMP stores every pixel's raw color data with no compression. A 1920×1080 BMP is about 6 MB; the same image as JPG at 90% quality is under 1 MB." },
      { q: "Is quality preserved when converting BMP to JPG?", a: "At 90% quality, the JPG looks virtually identical to the BMP original. There's slight lossy compression, but it's imperceptible." },
      { q: "Is the BMP file uploaded to a server?", a: "No. Conversion happens entirely in your browser using the Canvas API." },
      { q: "Can I batch convert BMP files to JPG?", a: "Yes. Upload multiple BMPs and download all JPGs as a ZIP." },
      { q: "Does JPG support all the colors in a BMP?", a: "Yes. Both formats support full 24-bit color (16.7 million colors). BMP also supports 32-bit with alpha, but JPG doesn't support transparency." },
    ],
    relatedSlugs: ["jpg-to-png", "png-to-jpg", "webp-to-jpg"],
  },
  {
    slug: "gif-to-jpg",
    fromFormat: "GIF",
    toFormat: "JPG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-fuchsia-500 to-pink-500",
    title: "GIF to JPG Converter — Free, No Upload, Instant",
    metaDescription: "Convert GIF to JPG free online. Extracts the first frame as a static JPG image. No upload, no signup, instant browser conversion.",
    h1: "Convert GIF to JPG — Free & Private",
    intro: "Need a static JPG from a GIF animation? ToolsHub converts GIF to JPG in your browser, extracting the first frame as a high-quality static image. Perfect for when you need a thumbnail, preview, or static version of an animated GIF.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the tool." },
      { title: "Upload your GIF file", desc: "Select your .gif file from your device." },
      { title: "Choose JPG output", desc: "Select JPG from the format dropdown." },
      { title: "Download the JPG", desc: "Download the static JPG extracted from your GIF." },
    ],
    useCases: [
      "Extract a static thumbnail from an animated GIF for preview images",
      "Convert a GIF logo to JPG for use in print documents",
      "Convert GIF images to JPG for platforms that don't support GIF",
      "Get a static frame from a GIF animation for a presentation slide",
      "Convert old GIF clip art to modern JPG format",
    ],
    alternatives: [
      { name: "Photoshop", issue: "Requires a paid subscription; overly complex for a simple conversion" },
      { name: "GIMP", issue: "Free but complex; requires multiple steps for GIF frame extraction" },
      { name: "Online converters", issue: "Most upload files to their servers" },
    ],
    faq: [
      { q: "Does GIF to JPG conversion keep the animation?", a: "No. JPG is a static format. The converter extracts the first frame of the GIF as a static JPG image." },
      { q: "Will colors be accurate in the JPG?", a: "GIF is limited to 256 colors, so the first-frame JPG will look the same as the GIF visually." },
      { q: "Is the GIF file uploaded to a server?", a: "No. Conversion runs locally in your browser." },
      { q: "Can I convert animated GIFs to video instead?", a: "Try the Video to GIF tool in reverse — or use the GIF → PNG option for a lossless static frame." },
      { q: "Can I batch convert GIFs to JPG?", a: "Yes. Upload multiple GIFs and download all first-frame JPGs in a ZIP." },
    ],
    relatedSlugs: ["gif-to-png", "jpg-to-png", "webp-to-jpg"],
  },
  {
    slug: "gif-to-png",
    fromFormat: "GIF",
    toFormat: "PNG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-violet-500 to-fuchsia-500",
    title: "GIF to PNG Converter — Free, No Upload, Preserve Quality",
    metaDescription: "Convert GIF to PNG free online. Lossless PNG output from GIF images. No upload, no signup. Batch convert in your browser.",
    h1: "Convert GIF to PNG — Free & Private",
    intro: "Converting a GIF to PNG gives you a lossless static image with better color depth than GIF (which is limited to 256 colors). PNG also supports full transparency, making it a better choice for logos and graphics. ToolsHub converts GIF to PNG locally in your browser — no uploads.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the tool." },
      { title: "Upload your GIF", desc: "Drop your GIF file into the upload zone." },
      { title: "Select PNG output", desc: "Choose PNG from the format selector." },
      { title: "Download the PNG", desc: "Download your lossless PNG image." },
    ],
    useCases: [
      "Convert GIF logos to PNG for sharper rendering on retina displays",
      "Convert GIF clip art to PNG for transparent background editing",
      "Convert static GIF images to PNG for higher color fidelity",
      "Convert GIF icons to PNG for use in mobile apps",
      "Convert GIF thumbnails to PNG for professional presentations",
    ],
    alternatives: [
      { name: "GIMP", issue: "Powerful but complex for a simple conversion task" },
      { name: "Cloudconvert", issue: "Server-side conversion; files uploaded to their cloud" },
      { name: "ImageMagick", issue: "Command-line tool requiring technical knowledge" },
    ],
    faq: [
      { q: "Will converting GIF to PNG preserve transparency?", a: "Yes. Both GIF and PNG support transparency. The transparent areas in a GIF will be preserved in the PNG output." },
      { q: "Is the PNG animation-capable like GIF?", a: "Standard PNG is static. APNG supports animation, but the Image Converter outputs static PNG." },
      { q: "Why is PNG better than GIF for static images?", a: "PNG supports millions of colors and full alpha transparency, while GIF is limited to 256 colors and binary transparency." },
      { q: "Is the GIF uploaded to any server?", a: "No. The conversion runs locally in your browser using the Canvas API." },
      { q: "Can I batch convert GIFs to PNG?", a: "Yes. Upload multiple GIF files and download all PNGs in a ZIP archive." },
    ],
    relatedSlugs: ["gif-to-jpg", "png-to-webp", "webp-to-png"],
  },
  {
    slug: "tiff-to-jpg",
    fromFormat: "TIFF",
    toFormat: "JPG",
    toolHref: "/image-converter",
    category: "image",
    accentColor: "from-teal-500 to-cyan-500",
    title: "TIFF to JPG Converter — Free, No Upload, Instant",
    metaDescription: "Convert TIFF to JPG free online. Reduce large TIFF files to web-friendly JPG. No upload, no signup, instant browser conversion.",
    h1: "Convert TIFF to JPG — Free & Private",
    intro: "TIFF files are uncompressed or lightly compressed, making them enormous. A professional TIFF from a scanner or DSLR can easily be 50–200 MB. Converting to JPG reduces file size by 90%+ while maintaining excellent visual quality. ToolsHub converts TIFF to JPG locally in your browser.",
    steps: [
      { title: "Open the Image Converter", desc: "Click the button below to open the tool." },
      { title: "Upload your TIFF file", desc: "Select your .tiff or .tif file." },
      { title: "Choose JPG output", desc: "Select JPG and set quality (90% recommended)." },
      { title: "Download the JPG", desc: "Save your much-smaller JPG file." },
    ],
    useCases: [
      "Convert scanned TIFF documents to shareable JPG",
      "Convert DSLR TIFF exports to smaller JPG for web use",
      "Reduce TIFF archive file sizes for storage optimization",
      "Convert TIFF graphics to JPG for email sharing",
      "Convert professional print TIFF files to JPG for web previews",
    ],
    alternatives: [
      { name: "Photoshop", issue: "Requires paid subscription; overkill for simple format conversion" },
      { name: "Adobe Bridge", issue: "Requires Creative Cloud installation" },
      { name: "GIMP", issue: "Free but complex multi-step process for batch conversion" },
    ],
    faq: [
      { q: "Why are TIFF files so large?", a: "TIFF uses lossless or no compression, storing all pixel data. A single TIFF page from a scanner can be 50–200 MB." },
      { q: "Does converting TIFF to JPG lose quality?", a: "Slight quality loss due to JPG's lossy compression. At 90% quality, the difference is imperceptible for most uses." },
      { q: "Is the TIFF file sent to a server?", a: "No. The conversion is handled locally in your browser. Note that very large TIFF files may be slow due to browser memory limits." },
      { q: "Can I batch convert TIFFs to JPG?", a: "Yes. Upload multiple TIFF files and download all JPGs as a ZIP." },
      { q: "Does TIFF support multiple pages?", a: "TIFF can store multiple pages, but the Image Converter converts the first page to JPG. For multi-page documents, use the PDF converter." },
    ],
    relatedSlugs: ["bmp-to-jpg", "jpg-to-png", "webp-to-jpg"],
  },
  {
    slug: "pdf-to-jpg",
    fromFormat: "PDF",
    toFormat: "JPG",
    toolHref: "/pdf-converter",
    category: "pdf",
    accentColor: "from-red-500 to-rose-600",
    title: "PDF to JPG Converter — Free, No Upload, Instant",
    metaDescription: "Convert PDF to JPG free online. Each PDF page becomes a JPG image. No upload, no signup. Private browser-based processing.",
    h1: "Convert PDF to JPG — Free & Private",
    intro: "Need to extract pages from a PDF as JPG images? ToolsHub converts each PDF page to a high-quality JPG image entirely in your browser using PDF.js. Your document is never uploaded to any server — critical for confidential reports, contracts, and financial documents.",
    steps: [
      { title: "Open the PDF Tools", desc: "Click the button below to open the PDF converter." },
      { title: "Upload your PDF", desc: "Drop your PDF file into the upload area." },
      { title: "Select PDF to Image", desc: "Choose the 'PDF to Image' tab and select JPG format." },
      { title: "Download JPG images", desc: "Download each page as JPG or all pages as a ZIP." },
    ],
    useCases: [
      "Convert PDF slides to JPG images for PowerPoint or Keynote presentations",
      "Extract PDF pages as JPG images for social media posts",
      "Convert scanned PDF documents to JPG for OCR processing",
      "Convert PDF certificates or diplomas to JPG for digital sharing",
      "Extract product catalog PDF pages as JPG images for websites",
    ],
    alternatives: [
      { name: "Adobe Acrobat", issue: "Requires an expensive subscription ($14.99+/month)" },
      { name: "Smallpdf", issue: "Uploads your confidential documents to their servers" },
      { name: "ILovePDF", issue: "Server-side processing; limited free conversions" },
    ],
    faq: [
      { q: "Does PDF to JPG conversion preserve text quality?", a: "Yes. PDF.js renders each page at high DPI, resulting in sharp, readable JPG images of text and graphics." },
      { q: "Is my PDF document uploaded to a server?", a: "No. PDF.js processes your document entirely in your browser. Confidential documents stay private." },
      { q: "Can I convert a multi-page PDF to multiple JPGs?", a: "Yes. Each page of the PDF becomes a separate JPG image, all downloadable as a ZIP archive." },
      { q: "What resolution are the JPG images?", a: "The default resolution is 150 DPI, suitable for screen use. Higher DPI is recommended for print use." },
      { q: "Can I select specific pages to convert?", a: "Yes. You can choose which pages to convert or convert the entire PDF." },
    ],
    relatedSlugs: ["pdf-to-png", "pdf-to-webp", "jpg-to-pdf"],
  },
  {
    slug: "pdf-to-png",
    fromFormat: "PDF",
    toFormat: "PNG",
    toolHref: "/pdf-converter",
    category: "pdf",
    accentColor: "from-rose-500 to-pink-600",
    title: "PDF to PNG Converter — Free, Lossless, No Upload",
    metaDescription: "Convert PDF to PNG free online. Lossless PNG pages from any PDF. No upload, no signup, private browser-based processing.",
    h1: "Convert PDF to PNG — Free & Private",
    intro: "PDF to PNG conversion gives you lossless image quality from each PDF page — ideal for presentations, graphics, and any case where you need sharp, high-quality images without compression artifacts. ToolsHub processes your PDF entirely in your browser using PDF.js.",
    steps: [
      { title: "Open the PDF Tools", desc: "Click the button below to open the PDF converter." },
      { title: "Upload your PDF", desc: "Drop your PDF into the upload zone." },
      { title: "Choose PDF to Image → PNG", desc: "Select the PDF to Image tab and choose PNG format." },
      { title: "Download your PNGs", desc: "Download individual PNG pages or all as a ZIP." },
    ],
    useCases: [
      "Convert PDF pages to PNG for use in graphic design projects",
      "Extract PDF certificate pages as sharp PNG images",
      "Convert PDF slides to PNG for Figma or Sketch",
      "Convert PDF charts to PNG images for reports",
      "Get lossless page images from PDF for further editing",
    ],
    alternatives: [
      { name: "Adobe Acrobat", issue: "Expensive subscription required; overkill for simple conversions" },
      { name: "PDF24", issue: "Uploads your PDF to their servers for processing" },
      { name: "Zamzar", issue: "Requires account for large files; cloud-based processing" },
    ],
    faq: [
      { q: "Why choose PNG over JPG for PDF conversion?", a: "PNG is lossless — text and graphics are rendered with pixel-perfect sharpness. Choose PNG when quality matters more than file size." },
      { q: "Is my PDF uploaded to any server?", a: "No. PDF.js runs locally in your browser. Your document never leaves your device." },
      { q: "Can I convert all pages of a PDF to PNG?", a: "Yes. Each page becomes a separate PNG file. Download all as a ZIP archive." },
      { q: "What DPI are the PNG outputs?", a: "Default is 150 DPI (clear for screen use). The tool lets you choose higher DPI for print-quality output." },
      { q: "Will the PDF's fonts and colors look accurate?", a: "Yes. PDF.js renders fonts and colors accurately for most standard PDFs." },
    ],
    relatedSlugs: ["pdf-to-jpg", "pdf-to-webp", "png-to-pdf"],
  },
  {
    slug: "pdf-to-webp",
    fromFormat: "PDF",
    toFormat: "WebP",
    toolHref: "/pdf-converter",
    category: "pdf",
    accentColor: "from-red-500 to-orange-500",
    title: "PDF to WebP Converter — Free, Web-Optimized, No Upload",
    metaDescription: "Convert PDF to WebP free. Optimized web images from PDF pages. No upload, no signup, browser-based private processing.",
    h1: "Convert PDF to WebP — Free & Private",
    intro: "Converting PDF pages to WebP gives you web-optimized images that are smaller than JPG or PNG while maintaining excellent quality. Ideal for embedding PDF content on websites without the large file sizes of PNG. ToolsHub processes everything in your browser — your documents are never uploaded.",
    steps: [
      { title: "Open the PDF Tools", desc: "Click the button below to open the PDF converter." },
      { title: "Upload your PDF", desc: "Drop your PDF into the upload area." },
      { title: "Select PDF to Image → WebP", desc: "Choose the PDF to Image tab and select WebP format." },
      { title: "Download WebP images", desc: "Download your optimized WebP page images." },
    ],
    useCases: [
      "Convert PDF portfolio pages to WebP for fast website display",
      "Convert PDF infographic pages to WebP for blog posts",
      "Convert PDF product catalog pages to WebP for e-commerce",
      "Embed PDF report pages on a website as WebP images",
      "Convert PDF slide previews to WebP for web landing pages",
    ],
    alternatives: [
      { name: "PDF to JPG then JPG to WebP", issue: "Double conversion; extra quality loss and extra steps" },
      { name: "Adobe Acrobat", issue: "Doesn't export to WebP; only JPG, PNG, TIFF" },
      { name: "CloudConvert", issue: "Server-side processing; files uploaded to their cloud" },
    ],
    faq: [
      { q: "Why use WebP instead of JPG for PDF page images?", a: "WebP is 25–35% smaller than equivalent JPG quality, making your web pages load faster." },
      { q: "Is my PDF sent to any server?", a: "No. PDF.js and the Canvas API process your PDF entirely in your browser." },
      { q: "Do all browsers support WebP images?", a: "Yes. All modern browsers (Chrome, Firefox, Safari 14+, Edge) support WebP." },
      { q: "Can I convert a multi-page PDF to WebP?", a: "Yes. Each page becomes a WebP image, downloadable individually or as a ZIP." },
      { q: "What quality should I choose for PDF to WebP?", a: "80–85% quality gives an excellent balance of visual quality and small file size for web use." },
    ],
    relatedSlugs: ["pdf-to-jpg", "pdf-to-png", "jpg-to-webp"],
  },
  {
    slug: "jpg-to-pdf",
    fromFormat: "JPG",
    toFormat: "PDF",
    toolHref: "/pdf-converter",
    category: "pdf",
    accentColor: "from-red-600 to-rose-500",
    title: "JPG to PDF Converter — Free, No Upload, Merge Multiple",
    metaDescription: "Convert JPG to PDF free online. Combine multiple JPG images into one PDF. No upload, no signup, private browser processing.",
    h1: "Convert JPG to PDF — Free & Private",
    intro: "Need to turn your JPG photos into a PDF? ToolsHub converts one or multiple JPG images into a single PDF document entirely in your browser. Combine multiple JPGs into one PDF for sharing, printing, or archiving — with zero uploads and zero cost.",
    steps: [
      { title: "Open the PDF Tools", desc: "Click the button below to open the PDF converter." },
      { title: "Upload your JPG images", desc: "Drop one or multiple JPG files into the upload zone." },
      { title: "Select Image to PDF", desc: "Choose the Image to PDF tab in the PDF Tools." },
      { title: "Download your PDF", desc: "All JPGs are combined into one PDF. Click Download." },
    ],
    useCases: [
      "Combine scanned JPG pages into a single PDF document",
      "Convert JPG photos of receipts or invoices into a PDF",
      "Submit JPG images as PDF for forms or applications",
      "Combine JPG photos of ID documents into one PDF",
      "Create a PDF portfolio from JPG photographs",
    ],
    alternatives: [
      { name: "Adobe Acrobat", issue: "Expensive subscription; not needed for a simple JPG-to-PDF task" },
      { name: "Smallpdf", issue: "Uploads your images to their servers" },
      { name: "Word (Insert Images)", issue: "Requires Microsoft Office; complex for a simple conversion" },
    ],
    faq: [
      { q: "Can I combine multiple JPG images into one PDF?", a: "Yes. Upload multiple JPGs and they will all be combined into a single multi-page PDF." },
      { q: "Is my JPG uploaded to a server?", a: "No. The pdf-lib library processes your images locally in your browser." },
      { q: "Can I control the page size and orientation?", a: "Yes. The tool lets you choose page size (A4, Letter) and portrait or landscape orientation." },
      { q: "Does the PDF support high-quality printing?", a: "Yes. JPG images are embedded at their original resolution in the PDF, maintaining print quality." },
      { q: "Can I also convert PNG to PDF?", a: "Yes. The Image to PDF tool accepts JPG, PNG, and WebP images." },
    ],
    relatedSlugs: ["png-to-pdf", "pdf-to-jpg", "image-to-pdf"],
  },
  {
    slug: "png-to-pdf",
    fromFormat: "PNG",
    toFormat: "PDF",
    toolHref: "/pdf-converter",
    category: "pdf",
    accentColor: "from-indigo-500 to-purple-600",
    title: "PNG to PDF Converter — Free, No Upload, Merge Multiple",
    metaDescription: "Convert PNG to PDF free online. Combine PNG images into PDF documents. No upload, no signup, private browser processing.",
    h1: "Convert PNG to PDF — Free & Private",
    intro: "Convert your PNG images to PDF for sharing, archiving, or printing. ToolsHub combines one or multiple PNG files into a single PDF entirely in your browser — no uploads, no privacy concerns, completely free.",
    steps: [
      { title: "Open the PDF Tools", desc: "Click the button below to open the PDF converter." },
      { title: "Upload your PNG files", desc: "Select one or multiple PNG images." },
      { title: "Choose Image to PDF", desc: "Select the Image to PDF tab." },
      { title: "Download your PDF", desc: "All PNGs are merged into one PDF. Download instantly." },
    ],
    useCases: [
      "Convert PNG screenshots to a single PDF document",
      "Combine PNG design mockups into a PDF for client review",
      "Convert PNG diagrams and charts to PDF for reports",
      "Convert PNG scans of documents into PDF format",
      "Combine PNG wireframes into a PDF presentation",
    ],
    alternatives: [
      { name: "Word (Insert Images)", issue: "Requires Microsoft Office and multiple steps" },
      { name: "ILovePDF", issue: "Uploads your PNGs to their servers" },
      { name: "Preview (macOS)", issue: "Only available on Mac; limited batch options" },
    ],
    faq: [
      { q: "Can I combine multiple PNGs into one PDF?", a: "Yes. Upload multiple PNG files and they are all included as pages in a single PDF." },
      { q: "Is my PNG file uploaded to any server?", a: "No. pdf-lib processes your images locally in your browser." },
      { q: "Does the PNG's transparency appear in the PDF?", a: "PNG transparency is rendered against a white background in the PDF, as PDF doesn't natively support PNG alpha in all contexts." },
      { q: "Can I also include JPG images in the same PDF?", a: "Yes. The Image to PDF tool accepts JPG, PNG, and WebP. Mix formats in one PDF." },
      { q: "What page size will my PDF be?", a: "You can choose A4, US Letter, or have the page match the image dimensions." },
    ],
    relatedSlugs: ["jpg-to-pdf", "image-to-pdf", "pdf-to-png"],
  },
  {
    slug: "image-to-pdf",
    fromFormat: "Image",
    toFormat: "PDF",
    toolHref: "/pdf-converter",
    category: "pdf",
    accentColor: "from-red-500 to-pink-600",
    title: "Image to PDF Converter — Free, No Upload, Any Format",
    metaDescription: "Convert images to PDF free online. JPG, PNG, WebP to PDF. No upload, no signup. Combine multiple images into one PDF.",
    h1: "Convert Images to PDF — Free & Private",
    intro: "Convert any image (JPG, PNG, WebP) to a PDF document instantly. ToolsHub lets you combine multiple images into one PDF, adjust page settings, and download the result — all in your browser without uploading anything to a server.",
    steps: [
      { title: "Open the PDF Tools", desc: "Click the button below to open the converter." },
      { title: "Upload your images", desc: "Select JPG, PNG, or WebP images (or mix them)." },
      { title: "Select Image to PDF", desc: "Choose the Image to PDF tab and set page options." },
      { title: "Download your PDF", desc: "All images are combined into one PDF. Download instantly." },
    ],
    useCases: [
      "Scan documents with your phone camera and convert photos to PDF",
      "Combine product photos into a PDF catalog",
      "Submit multiple images as a single PDF application",
      "Convert photo archives to PDF for organized storage",
      "Create a PDF photo book from image files",
    ],
    alternatives: [
      { name: "Adobe Acrobat", issue: "Expensive subscription not justified for basic image-to-PDF conversion" },
      { name: "Google Drive", issue: "Uploads your images to Google's servers" },
      { name: "Smallpdf", issue: "Server-side; limited free conversions and file size" },
    ],
    faq: [
      { q: "What image formats are supported?", a: "JPG, JPEG, PNG, and WebP. Mix different formats in the same PDF." },
      { q: "Is there a limit on how many images I can combine?", a: "No server-side limit. Very large batches may be slower due to browser memory." },
      { q: "Are my images uploaded to a server?", a: "No. pdf-lib processes everything locally in your browser." },
      { q: "Can I choose the PDF page size?", a: "Yes. Choose A4, US Letter, or fit the page to the image dimensions." },
      { q: "Can I reorder images before creating the PDF?", a: "Yes. Drag to reorder images in the tool before generating the PDF." },
    ],
    relatedSlugs: ["jpg-to-pdf", "png-to-pdf", "pdf-to-jpg"],
  },
];

export const CONVERSION_BY_SLUG = new Map(CONVERSIONS.map((c) => [c.slug, c]));

export const IMAGE_CONVERSIONS = CONVERSIONS.filter((c) => c.category === "image");
export const PDF_CONVERSIONS = CONVERSIONS.filter((c) => c.category === "pdf");
